### ISSUE TITLE
tinydtls dtls-client and dtls server not doing handshaking

### ISSUE THREAD

**Issue by NitinLnt** [thecodemaiden/tinydtls-coap#1]
Hi I am trying to make communicate between client & server locally and getting following error,

SERVER
sysadmin@BLTSP00023:~/workspace/abc/dtls$ ./tests/dtls-server
Jan 18 15:21:51 WARN cannot verify peer

CLIENT
root@BLTSP00023:/home/sysadmin/workspace/abc/dtls# ./tests/dtls-client 127.0.0.1 20220
Jan 18 15:22:11 � ��� ��ALRT setsockopt IPV6_PKTINFO: Protocol not available

And I verified IPV6 is enables in my system
Please help me understand whare I am wrong

**Comment by thecodemaiden** [comment]
It's been a wile since I looked at libcoap and tinydtls, but I believe they are using IPv6.  You can't use addresses like 127.0.0.1, as this is an IPv4 address. Try using ::1, which is the localhost address in IPv6.

**Comment by NitinLnt** [comment]
Thank you, I changed commands to
./dtls-server
and ./tests/dtls-client ::1
But I am not getting any output here, Am I missing something now also?

**Comment by thecodemaiden** [comment]
From looking at the source, it seems the dtls examples expect you to type something in at the client and see it received at the server. What is your input to the client?

**Comment by NitinLnt** [comment]
Thanks I changed code into IPv4 at protocol level, After that it is working with below commands
 ./tests/dtls-server
./test/dtls-client 127.0.0.1
Sorry for late reply ..

**Comment by ghost** [comment]
Hi Sir,
I tried to execute the following commands ./tests/dtls-server
./test/dtls-client 127.0.0.1 but am not getting proper output.The connection is also not being established. i got a warning as WARN cannot verify peer. And also I tried with ipv6 address also(./tests/dtls-client ::1).Please help me to solve the error.
gmail :- nandhinigiri28@gmail.com
